### ISSUE TITLE
feat: whois slack bot

### ISSUE THREAD

**Issue by nimish-gupta** [remoteindian/remoteindian#17]
Fetch all intros from RI intro channel into Hasura database. Create a slack bot which allows anyone to fetch that info.

Idea - [here](https://remoteindian.nolt.io/7)

Slack Conversation - [here](https://remoteindian.slack.com/archives/C016TDHA4FM/p1595310107001000)

**Comment by nimish-gupta** [comment]
Hey @abhishekbose87, can you go ahead and populate the Hasura database with all the intros?

How will the new entries be stored in the database, will you be running them periodically? Or a listening event in intro channel which will automatically store it in the database?

**Comment by abhishekbose87** [comment]
Hey @nimish-gupta, Thanks for starting this conversation. 

How about you create a mock graphql api for your dev purposes. That way the specs will be well-defined. Let me know if that works for you.

> How will the new entries be stored in the database, will you be running them periodically?

The plan, for now, is to do this manually. I will update the database at least once a month.

**Comment by nimish-gupta** [comment]
Also, do we want the response in just plain text or something using blocks from [this](https://github.com/speee/jsx-slack)?

> How about you create a mock graphql api for your dev purposes. That way the specs will be well-defined. Let me know if that works for you.

Are we using graphql here? or you are saying in the context of Hasura. I was thinking of opening a rest end point.

**Comment by nimish-gupta** [comment]
I have created [this](https://github.com/nimish-gupta/who-is) bot for now. It's still a first version. 

Closing this issue for now.
